services:
  auth:
    container_name: ticketing-auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: dev
    command: sh -c '/wait && npm run start:dev auth'
    env_file:
      - ./apps/auth/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/opt/nest_app
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      disable: true

  ticket:
    container_name: ticketing-ticket
    build:
      context: .
      dockerfile: ./apps/ticket/Dockerfile
      target: dev
    command: sh -c '/wait && npm run start:dev ticket'
    env_file:
      - ./apps/ticket/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/opt/nest_app
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      disable: true

  db:
    container_name: ticketing-db
    image: mysql:8.0.33-debian
    cap_add:
      - SYS_NICE
    ports:
      - '3307:3306'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ticketing
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p$$MYSQL_ROOT_PASSWORD',
        ]
      interval: 5s
      timeout: 4s
      retries: 5
      start_period: 10m

volumes:
  db:
